baseURL = "http://example.org/"
languageCode = "de-de"
title = "Isabell Martins"
theme = "hugo-scroll"
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]
[permalinks]
    pages = "/:slug/"