baseURL = "http://example.org/"
languageCode = "de-de"
title = "Isabell Martins"
theme = "hugo-scroll"
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]
[permalinks]
    page = "/:slug/"
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            hardWraps = true
[params]
    homepageHeaderImage = "/images/background_1430507946121-1431629532548.jpg"
