baseURL = "http://example.org/"
languageCode = "en-us"
title = "Isabell Martins"
# disableKinds = ["page", "home", "section", "taxonomy", "term", "RSS", "sitemap", "robotsTXT", "404"]
theme = "hugo-scroll"
disableKinds = ["taxonomy", "term", "RSS"]
