baseURL = "https://www.isabellmartins.de"
defaultContentLanguage = "de"
title = "Isabell Martins"
theme = "hugo-scroll"
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            hardWraps = true
[menu]
  [[menu.main]]
    name = "Leistungen"
    url = "#leistungen"
    weight = 1
  [[menu.main]]
    name = "Über Mich"
    url = "#über-mich"
    weight = 2
  [[menu.main]]
    name = "Kontakt"
    url = "#kontakt"
    weight = 3
[params]
    title = "Isabell Martins"
    description = "Individuelle und ganzheitliche Ernährungsberatung in Lübeck"
    images = ["/images/background_1430507946121-1431629532548.jpg"]
    favicon = "favicon.png"
    [params.meta]
        keywords = "ganzheitlich, ernährung, ernährungsberatung, lübeck"
[permalinks]
    page = "/:slug/"
