[build]
publish = "public"
command = "npx tinacms build && hugo --gc --minify && hugo --gc --minify --source hunde --destination ../public/hunde"

[context.production.environment]
HUGO_VERSION = "v0.121.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "v0.121.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "npx tinacms build && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL && hugo --gc --minify --source hunde --baseURL $DEPLOY_PRIME_URL/hunde --destination ../public/hunde"

[context.deploy-preview.environment]
HUGO_VERSION = "v0.121.1"

[context.branch-deploy]
command = "npx tinacms build && hugo --gc --minify -b $DEPLOY_PRIME_URL  && hugo --gc --minify --source hunde --baseURL $DEPLOY_PRIME_URL/hunde --destination ../public/hunde"

[context.branch-deploy.environment]
HUGO_VERSION = "v0.121.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

# Redirects and headers are GLOBAL for all builds – they do not get scoped to
# contexts no matter where you define them in the file.
# For context-specific rules, use _headers or _redirects files, which are
# PER-DEPLOY.

[[redirects]]
  from = "http://agitated-euclid-60fa30.netlify.app/*"
  to = "http://www.isabellmartins.de/:splat"
  force = true
  status = 301

[[redirects]]
  from = "https://agitated-euclid-60fa30.netlify.app/*"
  to = "https://www.isabellmartins.de/:splat"
  force = true
  status = 301

[[redirects]]
  from = "https://hunde.isabellmartins.de/*"
  to = "/hunde/:splat"
  force = true
  status = 200

[[redirects]]
  from = "https://www.isabellmartins.de/hunde/*"
  to = "https://hunde.isabellmartins.de/:splat"
  force = true
  status = 301

[[redirects]]
  from = "http://hunde.isabellmartins.de/*"
  to = "https://hunde.isabellmartins.de/:splat"
  force = true
  status = 301

[[redirects]]
  from = "https://hund.isabellmartins.de/*"
  to = "https://hunde.isabellmartins.de/:splat"
  force = true
  status = 301

[[redirects]]
  from = "http://hund.isabellmartins.de/*"
  to = "https://hunde.isabellmartins.de/:splat"
  force = true
  status = 301
