[build]
publish = "public"
command = "git submodule update --init --recursive && hugo --gc --minify && hugo --gc --minify --source hunde --baseURL https://www.isabellmartins.de/hunde --destination ../public/hunde"

[context.production.environment]
HUGO_VERSION = "0.73.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.73.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL && hugo --gc --minify --source hunde --baseURL $DEPLOY_PRIME_URL/hunde --destination ../public/hunde"

[context.deploy-preview.environment]
HUGO_VERSION = "0.73.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL  && hugo --gc --minify --source hunde --baseURL $DEPLOY_PRIME_URL/hunde --destination ../public/hunde"

[context.branch-deploy.environment]
HUGO_VERSION = "0.73.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"


# Redirects and headers are GLOBAL for all builds – they do not get scoped to
# contexts no matter where you define them in the file.
# For context-specific rules, use _headers or _redirects files, which are
# PER-DEPLOY.

[[redirects]]
  from = "http://dreamy-einstein-14578e.netlify.app/*"
  to = "http://www.isabellmartins.de/:splat"
  force = true
  status = 301

[[redirects]]
  from = "https://dreamy-einstein-14578e.netlify.app/*"
  to = "https://www.isabellmartins.de/:splat"
  force = true
  status = 301
