---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Homepage
- type: document
  path: hunde/content/_index.md
  label: Willkommen
- type: document
  path: hunde/data/counter.yml
  label: Zahlen for Fun
- type: document
  path: hunde/data/call_to_action.yml
  label: Call To Action
- type: document
  path: hunde/data/hero.yml
  label: Hero
- type: heading
  label: Team
- type: document
  path: hunde/content/team/_index.md
  label: Teambereich
- type: heading
  label: Kontakt
- type: document
  path: hunde/content/contact/_index.md
  label: Kontaktformular
- type: heading
  label: Allgemein
- type: document
  path: hunde/data/footer.yml
  label: Footer
upload_dir: hunde/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: public/hunde
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    --source hunde --destination ../public/hunde
version: 0.71.1
