# see https://www.netlifycms.org/docs/add-to-your-site/
backend:
  name: git-gateway
logo_url: https://hunde.isabellmartins.de/images/logo.png
display_url: https://hunde.isabellmartins.de
media_folder: 'hunde/static/images' # Media files will be stored in the repo under static/images
public_folder: '/images' # The src attribute for uploaded media will begin with /images
collections: # A list of collections the CMS should be able to edit
  - name: 'hunde'
    editor:
      preview: false
    label: 'Hunde' # Used in the UI, ie.: "New Page"
    files:
      - label: 'Home - Seite'
        name: "homepage"
        file: 'hunde/content/_index.md'
        fields:
          - label: 'Titel'
            name: 'title'
            widget: 'string'
            hint: 'Der Titel oben in der Tableiste des Browsers'
          - label: "Content"
            name: "body"
            widget: "markdown"
            default: 'Here goes the content... With **markdown**...'
      - label: 'Hero - Bereich'
        name: 'hero'
        file: 'hunde/data/hero.yml'
        fields:
          - label: 'Hero Anzeigen?'
            name: 'enable'
            widget: boolean
          - label: 'Hintergrund Bild'
            name: 'background_image'
            widget: 'image'
            allow_multiple: false
          - label: 'Erste Zeile der Überschrift'
            name: 'heading_line_1'
            widget: 'string'
          - label: 'Zweite Zeile der Überschrift'
            name: 'heading_line_2'
            widget: 'string'
          - label: 'Tagline'
            name: 'tagline'
            widget: 'string'
          - label: 'Button Text'
            name: 'button'
            widget: 'string'
          - label: 'Button Link'
            name: 'button_url'
            widget: 'string'
      - label: 'Call To Action - Bereich'
        name: 'cta'
        file: 'hunde/data/call_to_action.yml'
        fields:
          - label: '»Call To Action« Bereich anzeigen?'
            name: 'enable'
            widget: 'boolean'
          - label: 'Hintergrund Bild'
            name: 'background_image'
            widget: 'image'
            allow_multiple: false
          - label: 'Überschrift'
            name: 'title'
            widget: 'string'
          - label: 'Button Text'
            name: 'primary_button'
            widget: 'string'
          - label: 'Button Link'
            name: 'primary_button_url'
            widget: 'string'
      - label: 'Zahlen for Fun :-) - Bereich'
        name: 'counter'
        file: 'hunde/data/counter.yml'
        fields:
          - label: 'Zahlen for Fun anzeigen?'
            name: 'enable'
            widget: 'boolean'
          - label: 'Überschrift'
            name: 'heading'
            widget: 'string'
          - label: 'Zahlen'
            name: 'counter_item'
            widget: 'list'
            fields:
              - label: 'Titel'
                name: 'title'
                widget: 'string'
              - label: 'Anzahl'
                name: 'number'
                widget: 'string'
      - label: 'Kontakt Formular - Seite'
        name: "kontakt"
        file: 'hunde/content/contact/_index.md'
        fields:
          - label: 'Titel'
            name: 'title'
            widget: 'string'
            hint: 'Der Titel oben in der Tableiste des Browsers'
          - label: 'Große Überschrift'
            name: 'heading'
            widget: 'string'
            required: true
          - label: 'Kleine Überschrift'
            name: 'form_heading'
            widget: 'string'
            required: true
          - label: 'Name des Formulars'
            name: 'form_name'
            widget: 'string'
            hint: 'Für die Anzeige in Netlify >> Forms'
            required: true
          - label: 'Formular: E-Mail-Adresse Platzhalter'
            name: 'form_field_email_placeholder'
            widget: 'string'
            required: true
          - label: 'Formular: E-Mail-Adresse Notwendig?'
            name: 'form_field_email_required'
            widget: 'boolean'
            required: true
          - label: 'Formular: Nachname Platzhalter'
            name: 'form_field_lastname_placeholder'
            widget: 'string'
            required: true
          - label: 'Formular: Nachname Notwendig?'
            name: 'form_field_lastname_required'
            widget: 'boolean'
            required: true
          - label: 'Formular: Vorname Platzhalter'
            name: 'form_field_name_placeholder'
            widget: 'string'
            required: true
          - label: 'Formular: Vorname Notwendig?'
            name: 'form_field_name_required'
            widget: 'boolean'
            required: true
          - label: 'Formular: Telefon Platzhalter'
            name: 'form_field_tel_placeholder'
            widget: 'string'
            required: true
          - label: 'Formular: Telefon Notwendig?'
            name: 'form_field_tel_required'
            widget: 'boolean'
            required: true
          - label: 'Formular: Text Platzhalter'
            name: 'form_field_text_placeholder'
            widget: 'string'
            required: true
          - label: 'Formular: Text Notwendig?'
            name: 'form_field_text_required'
            widget: 'boolean'
            required: true
          - label: 'Formular: Button'
            name: 'form_submit_button_text'
            widget: 'string'
            required: true
          - label: 'Formular: Success-Message'
            name: 'form_submit_success_text'
            widget: 'string'
            required: true
            hint: 'Wird angezeigt nach erfolgreichem Abschicken des Formulars'
          - label: 'Formular: Error-Message'
            name: 'form_submit_error_text'
            widget: 'string'
            required: true
            hint: 'Wird angezeigt, wenn beim Senden des Formulars ein Fehler auftritt'
      - label : 'Footer - Bereich'
        name: 'footer'
        file: 'hunde/data/footer.yml'
        fields:
          - label: 'Kontakt'
            name: 'contactInfo'
            widget: 'object'
            fields:
              - label: 'Titel'
                name: 'title'
              - label: 'Telefon'
                name: 'phone'
              - label: 'Email'
                name: 'email'
          - label: 'Sitemap'
            name: 'sitemap'
            widget: 'object'
            fields:
             - label: 'Titel'
               name: 'title'
             - label: 'Links'
               name: 'link'
               widget: 'list'
               fields:
                - label: 'Name'
                  name: 'name'
                - label: 'URL'
                  name: 'url'
          - label: 'Rechtliches'
            name: 'legal'
            widget: 'object'
            fields:
             - label: 'Titel'
               name: 'title'
             - label: 'Links'
               name: 'link'
               widget: 'list'
               fields:
                - label: 'Name'
                  name: 'name'
                - label: 'URL'
                  name: 'url'
          - label: 'Zurück nach oben - Text'
            name: 'back_to_top_button_text'
